---
- hosts: 35.162.221.76
  remote_user: root
  become: yes

  vars:
    zabbix_proxy_ip: 192.168.10.xxx
    zabbix_proxy_name: zabbix_srv_aws
    Hostname: 35.162.221.76
    host_connect_ip: 192.168.10.116

  tasks:
  - name: add group "zabbix"
    group: name=zabbix

  - name: add user "zabbix"
    user: name=zabbix group=zabbix home=/sbin/nologin createhome=no
        
  - name: unarchive zabbix agent to hosts
    unarchive: src="/home/deploy/zabbix_agent/zabbix_agent.tar.gz" dest="/usr/local/"
        
  - name: add zabbix server in /etc/hosts       
    lineinfile: dest=/etc/hosts line="{{ zabbix_proxy_ip }} {{ zabbix_proxy_name }}" state=present

  - name: Configure zabbix agent
    template: src=/home/deploy/zabbix_agent/zabbix_agentd.conf dest=/usr/local/zabbix/etc/zabbix_agentd.conf
    notify: start zabbix
        
  handlers:
    - name: start zabbix
      command: /usr/local/zabbix/sbin/zabbix_agentd -c /usr/local/zabbix/etc/zabbix_agentd.conf

